# Generated by Django 4.2.11 on 2024-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ipaddress",
            field=models.GenericIPAddressField(null=True, blank=True),
        ),
    ]
