# Generated by Django 4.2.11 on 2024-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_ipaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ipaddress",
            field=models.CharField(max_length=128),
        ),
    ]
