# Generated by Django 4.2.11 on 2024-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_user_ipaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ipaddress",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
