# Generated by Django 4.2.11 on 2024-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_user_ipaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ipaddress",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
