# Generated by Django 4.2.11 on 2024-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_rename_user_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="ipaddress",
            field=models.GenericIPAddressField(),
        ),
    ]
