# Generated by Django 4.2.11 on 2024-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_users_ipaddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="save_gaze_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gaze_x", models.IntegerField()),
                ("gaze_y", models.IntegerField()),
            ],
        ),
    ]
